config/routes.rb
BusinessCms::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

    resources :products, only: [:index, :show]
    resources :blog, only: [:index, :show]
    resources :projects, only: [:index, :show]
    resources :services, only: [:index, :show]

    get 'about' => 'pages#about'
    get 'faq'   => 'pages#faq'
    get 'contact' => 'pages#contact'
    post 'save_contact' => 'pages#save_contact'

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :image, :post, :published, :title

  has_many :categorizations
  has_many :categories, :through => :categorizations
  belongs_to :admin_user

  # uploader
  mount_uploader :image, BlogImageUploader
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :blog_id, :category_id

  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :categorizations
  has_many :blogs, :through => :categorizations
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  attr_accessible :key, :value
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :about, :image, :name, :website, :priority, :published

  # Uploader
  mount_uploader :image, CustomerImageUploader
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :description, :priority, :published, :title
end

app/models/home_slider.rb
class HomeSlider < ActiveRecord::Base
  attr_accessible :caption, :image, :priority, :published
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :priority, :title, :url
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :description, :image, :permalink, :published, :title

  # uploader
  mount_uploader :image, PageImageUploader

  PERMALINK = {
      about: 'about',
      faq: 'faq',
      contact: 'contact'
  }
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image, :priority, :published, :title

  # uploader
  mount_uploader :image, ProductImageUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :image1, :image2, :image3, :image4, :image5, :priority, :published, :title

  # Validations
  validates_presence_of :description, :title

  # uploader
  mount_uploader :image1, ProjectImage1Uploader
  mount_uploader :image2, ProjectImage2Uploader
  mount_uploader :image3, ProjectImage3Uploader
  mount_uploader :image4, ProjectImage4Uploader
  mount_uploader :image5, ProjectImage5Uploader
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :description, :image, :priority, :published, :title

  # Validations
  validates_presence_of :title, :description

  # uploader
  mount_uploader :image, ServiceImageUploader
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :about, :facebook_url, :google_talk_url, :image, :jobtitle, :linkedin_url,
                  :name, :priority, :published, :twitter_url

  # uploader
  mount_uploader :image, TeamImageUploader
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @services = Service.where(published: true).order('priority').limit(3)
    @about  = Page.find_by_permalink(Page::PERMALINK[:about])
    @projects = Project.where(published: true).order('priority').limit(6)

    @products = Product.where(published: true).order('priority').limit(2)
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/home/index.html.erb
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
      <div class="carousel-caption">
        <h1>Modern Business - A Bootstrap 3 Template</h1>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
      <div class="carousel-caption">
        <h1>Ready to Style &amp; Add Content</h1>
      </div>
    </div>
    <div class="item">
      <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
      <div class="carousel-caption">
        <h1>Additional Layout Options at <a href="http://startbootstrap.com">http://startbootstrap.com</a>
        </h1>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>

<div class="section">

  <div class="container">

    <div class="row">
      <% @services.each do |service| %>
          <div class="col-lg-4">
            <h2><%= service.title %></h2>
            <%= get_word_summery(service.description, 50).html_safe %>
            <a class="btn btn-link btn-sm" href="<%= service_path(service.id) %>">More <i class="fa fa-angle-right"></i></a>
          </div>
      <% end %>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

</div>
<!-- /.section -->

<div class="section-colored text-center">

  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <%= get_word_summery(@about.description, 50).html_safe %>
        <a class="btn btn-link btn-sm" href="<%= about_path %>">More <i class="fa fa-angle-right"></i></a>
        <hr>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

</div>
<!-- /.section-colored -->

<div class="section">

  <div class="container">

    <div class="row">
      <div class="col-lg-12 text-center">
        <h2>Display Some Work on the Home Page Portfolio</h2>
        <hr>
      </div>
      <% @projects.each do |project| %>
          <div class="col-lg-4 col-md-4 col-sm-6">

            <% if project.image1.present? %>
                <%= link_to image_tag(project.image1_url(:list), :class => 'img-responsive img-home-portfolio'), project_path(project.id) %>
            <% else %>
                <a href="<%= project_path(project.id) %>">
                  <img class="img-responsive" src="http://placehold.it/700x450">
                </a>
            <% end %>
          </div>
      <% end %>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

</div>
<!-- /.section -->

<% @products.each do |product| %>
    <div class="<%= product.priority == 1 ? 'section-colored' : 'section' %>">

      <div class="container">

        <div class="row">
          <% if product.priority == 1 %>
              <div class="col-lg-6 col-md-6 col-sm-6">
                <h2><%= product.title %></h2>
                <%= product.description.html_safe %>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6">
                <% if product.image.present? %>
                    <%= link_to image_tag(product.image_url(:main), :class => 'img-responsive'), product_path(product.id) %>
                <% else %>
                    <a href="<%= product_path(product.id) %>">
                      <img class="img-responsive" src="http://placehold.it/700x450">
                    </a>
                <% end %>
              </div>
          <% else %>
              <div class="col-lg-6 col-md-6 col-sm-6">
                <% if product.image.present? %>
                    <%= link_to image_tag(product.image_url(:main), :class => 'img-responsive'), product_path(product.id) %>
                <% else %>
                    <a href="<%= product_path(product.id) %>">
                      <img class="img-responsive" src="http://placehold.it/700x450">
                    </a>
                <% end %>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6">
                <h2><%= product.title %></h2>
                <%= product.description.html_safe %>
              </div>

          <% end %>
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container -->
    </div>
    <!-- /.section-colored -->
<% end %>