config/routes.rb
BusinessCms::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

    resources :products, only: [:index, :show]
    resources :blog, only: [:index, :show]
    resources :projects, only: [:index, :show]
    resources :services, only: [:index, :show]

    get 'about' => 'pages#about'
    get 'faq'   => 'pages#faq'
    get 'contact' => 'pages#contact'
    post 'save_contact' => 'pages#save_contact'

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :image, :post, :published, :title

  has_many :categorizations
  has_many :categories, :through => :categorizations
  belongs_to :admin_user

  # uploader
  mount_uploader :image, BlogImageUploader
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :blog_id, :category_id

  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :categorizations
  has_many :blogs, :through => :categorizations
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  attr_accessible :key, :value
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :about, :image, :name, :website, :priority, :published

  # Uploader
  mount_uploader :image, CustomerImageUploader
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :description, :priority, :published, :title
end

app/models/home_slider.rb
class HomeSlider < ActiveRecord::Base
  attr_accessible :caption, :image, :priority, :published
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :priority, :title, :url
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :description, :image, :permalink, :published, :title

  # uploader
  mount_uploader :image, PageImageUploader

  PERMALINK = {
      about: 'about',
      faq: 'faq',
      contact: 'contact'
  }
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image, :priority, :published, :title

  # uploader
  mount_uploader :image, ProductImageUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :image1, :image2, :image3, :image4, :image5, :priority, :published, :title

  # Validations
  validates_presence_of :description, :title

  # uploader
  mount_uploader :image1, ProjectImage1Uploader
  mount_uploader :image2, ProjectImage2Uploader
  mount_uploader :image3, ProjectImage3Uploader
  mount_uploader :image4, ProjectImage4Uploader
  mount_uploader :image5, ProjectImage5Uploader
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :description, :image, :priority, :published, :title

  # Validations
  validates_presence_of :title, :description

  # uploader
  mount_uploader :image, ServiceImageUploader
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :about, :facebook_url, :google_talk_url, :image, :jobtitle, :linkedin_url,
                  :name, :priority, :published, :twitter_url

  # uploader
  mount_uploader :image, TeamImageUploader
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Modern Business - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>

</head>

<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Project name', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/services">Services</a></li>
        <li><a href="/projects">Projects</a></li>
        <li><a href="/products">Products</a></li>
        <li><a href="/blog">Blog</a></li>
        <li><a href="/faq">Faq</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</div>

<%= yield %>

<div class="container">

  <hr>

  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Company 2013</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->

<!-- JavaScript -->
<%= javascript_include_tag 'application'  %>

</body>

</html>

app/views/pages/about.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">About</h1>
      <ol class="breadcrumb">
        <li><%= link_to 'Home', root_path %></li>
        <li class="active">About</li>
      </ol>
    </div>

  </div>

  <div class="row">

    <div class="col-md-6">
      <% if @about.image.present? %>
        <%= image_tag(@about.image_url(:main), :class => 'img-responsive') %>
      <% else %>
        <img class="img-responsive" src="http://placehold.it/750x450">
      <% end %>
    </div>
    <div class="col-md-6">
      <%= @about.description.html_safe %>
    </div>

  </div>

  <!-- Team Member Profiles -->
  <% if @teams.present? %>
  <div class="row">

    <div class="col-lg-12">
      <h2 class="page-header">Our Team</h2>
    </div>

    <% @teams.each do |team| %>
    <div class="col-sm-4">

      <% if team.image.present? %>
          <%= image_tag(team.image_url(:main), :class => 'img-responsive') %>
      <% else %>
          <img class="img-responsive" src="http://placehold.it/750x450">
      <% end %>
      <h3><% team.name %>
        <small><%= team.jobtitle %></small>
      </h3>
      <%= team.about.html_safe %>
      <ul class="list-unstyled list-inline list-social-icons">
        <li class="tooltip-social facebook-link"><a href="<%= team.facebook_url %>" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook-square fa-2x"></i></a>
        </li>
        <li class="tooltip-social linkedin-link"><a href="<%= team.linkedin_url %>" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="fa fa-linkedin-square fa-2x"></i></a>
        </li>
        <li class="tooltip-social twitter-link"><a href="<%= team.twitter_url %>" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter-square fa-2x"></i></a>
        </li>
        <li class="tooltip-social google-plus-link"><a href="<%= team.google_talk_url %>" data-toggle="tooltip" data-placement="top" title="Google+"><i class="fa fa-google-plus-square fa-2x"></i></a>
        </li>
      </ul>
    </div>
    <% end %>

  </div>
  <% end %>

  <!-- Our Customers -->

  <% if @customers.present? %>
  <div class="row">

    <div class="col-lg-12">
      <h2 class="page-header">Our Customers</h2>
    </div>

    <% @customers.each do |customer| %>

    <div class="col-md-2 col-sm-4 col-xs-6">

      <% if customer.image.present? %>
          <%= link_to image_tag(customer.image_url(:main), :class => 'img-responsive img-customer'), customer.website, target: '_blank' %>
      <% else %>
          <a href="<%= customer.website %>">
            <img class="img-responsive" src="http://placehold.it/500x300">
          </a>
      <% end %>
    </div>
    <% end %>

  </div>
  <% end %>
</div>
<!-- /.container -->

app/views/pages/contact.html.erb
<!-- Page Content -->

<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">Contact <small>We'd Love to Hear From You!</small></h1>
      <ol class="breadcrumb">
        <li><%= link_to 'Home', root_path %></li>
        <li class="active">Contact</li>
      </ol>
    </div>

    <div class="col-lg-12">
      <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
      <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
    </div>

  </div><!-- /.row -->

  <div class="row">

    <div class="col-sm-8">
      <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>

  <%= form_for @contact, url: save_contact_path do |f| %>
    <div class="row">
      <div class="form-group col-lg-6">
        <label for="input1">Name</label>
        <%= f.text_field :name , class: 'form-control' %>
      </div>
      <div class="form-group col-lg-6">
        <label for="input2">Email Address</label>
        <%= f.email_field :email , class: 'form-control' %>
      </div>
      <div class="clearfix"></div>
      <div class="form-group col-lg-12">
        <label for="input4">Message</label>
        <%= f.text_area :message , class: 'form-control' %>
      </div>
      <div class="form-group col-lg-12">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

<div class="col-sm-4">
  <h3>Modern Business</h3>
  <h4>A Start Bootstrap Template</h4>
  <p>
    5555 44th Street N.<br>
    Bootstrapville, CA 32323<br>
  </p>
  <p><i class="fa fa-phone"></i> <abbr title="Phone">P</abbr>: (555) 984-3600</p>
  <p><i class="fa fa-envelope-o"></i> <abbr title="Email">E</abbr>: <a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a></p>
  <p><i class="fa fa-clock-o"></i> <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
  <ul class="list-unstyled list-inline list-social-icons">
    <li class="tooltip-social facebook-link"><a href="#facebook-page" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook-square fa-2x"></i></a></li>
    <li class="tooltip-social linkedin-link"><a href="#linkedin-company-page" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="fa fa-linkedin-square fa-2x"></i></a></li>
    <li class="tooltip-social twitter-link"><a href="#twitter-profile" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter-square fa-2x"></i></a></li>
    <li class="tooltip-social google-plus-link"><a href="#google-plus-page" data-toggle="tooltip" data-placement="top" title="Google+"><i class="fa fa-google-plus-square fa-2x"></i></a></li>
  </ul>
</div>

</div><!-- /.row -->

</div><!-- /.container -->

app/views/pages/faq.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">FAQ
        <small>Frequently Asked Questions</small>
      </h1>
      <ol class="breadcrumb">
        <li><%= link_to 'Home', root_path %></li>
        <li class="active">FAQ</li>
      </ol>
    </div>

  </div>

  <div class="row">

    <div class="col-lg-12">

      <div class="panel-group" id="accordion">

        <% @faqs.each do |faq| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
               <%= faq.title %>
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
             <%= faq.description.html_safe %>
            </div>
          </div>
        </div>
        <% end %>

      </div>

    </div>

  </div>

</div>
<!-- /.container -->