config/routes.rb
BusinessCms::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

    resources :products, only: [:index, :show]
    resources :blog, only: [:index, :show]
    resources :projects, only: [:index, :show]
    resources :services, only: [:index, :show]

    get 'about' => 'pages#about'
    get 'faq'   => 'pages#faq'
    get 'contact' => 'pages#contact'
    post 'save_contact' => 'pages#save_contact'

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :image, :post, :published, :title

  has_many :categorizations
  has_many :categories, :through => :categorizations
  belongs_to :admin_user

  # uploader
  mount_uploader :image, BlogImageUploader
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :blog_id, :category_id

  belongs_to :blog
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :categorizations
  has_many :blogs, :through => :categorizations
end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
  attr_accessible :key, :value
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :about, :image, :name, :website, :priority, :published

  # Uploader
  mount_uploader :image, CustomerImageUploader
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :description, :priority, :published, :title
end

app/models/home_slider.rb
class HomeSlider < ActiveRecord::Base
  attr_accessible :caption, :image, :priority, :published
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :priority, :title, :url
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :description, :image, :permalink, :published, :title

  # uploader
  mount_uploader :image, PageImageUploader

  PERMALINK = {
      about: 'about',
      faq: 'faq',
      contact: 'contact'
  }
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image, :priority, :published, :title

  # uploader
  mount_uploader :image, ProductImageUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :image1, :image2, :image3, :image4, :image5, :priority, :published, :title

  # Validations
  validates_presence_of :description, :title

  # uploader
  mount_uploader :image1, ProjectImage1Uploader
  mount_uploader :image2, ProjectImage2Uploader
  mount_uploader :image3, ProjectImage3Uploader
  mount_uploader :image4, ProjectImage4Uploader
  mount_uploader :image5, ProjectImage5Uploader
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :description, :image, :priority, :published, :title

  # Validations
  validates_presence_of :title, :description

  # uploader
  mount_uploader :image, ServiceImageUploader
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :about, :facebook_url, :google_talk_url, :image, :jobtitle, :linkedin_url,
                  :name, :priority, :published, :twitter_url

  # uploader
  mount_uploader :image, TeamImageUploader
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.where(published: true)
    @blogs = @blogs.paginate(page: params[:page], per_page: 5)
  end

  def show
    @blog = Blog.find(params[:id])
    @categories = Category.all
  rescue
    redirect_to root_path, notice: 'No record found!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Get first few words
  def get_word_summery(string, count)
    string.split(" ").first(count).join(" ")
  end

  # Get first few char
  def get_char_summery(string, count)
    string[0..count]
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/blog/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header">Company Blog
      </h1>
      <ol class="breadcrumb">
        <li><%= link_to 'Home', root_path %></li>
        <li class="active">Blog</li>
      </ol>
    </div>

  </div>

  <% @blogs.each do |blog| %>
  <div class="row">

    <div class="col-md-1">
      <p><%= blog.created_at.strftime("%B %d, %Y") %></p>
    </div>
    <div class="col-md-5">
      <a href="<%= blog_path(blog.id) %>">

        <% if blog.image.present? %>
            <%= image_tag(blog.image_url(:main), :class => 'img-responsive') %>
        <% else %>
              <img class="img-responsive" src="http://placehold.it/600x300">
        <% end %>
      </a>
    </div>
    <div class="col-md-6">
      <h3><%= link_to blog.title, blog_path(blog.id) %></h3>
      <p>by <a href="#"><%= blog.admin_user.full_name %></a></p>
      <%= get_word_summery(blog.post.html_safe, 100).html_safe %>
      <a class="btn btn-link btn-sm" href="<%= blog_path(blog.id) %>">Read More <i class="fa fa-angle-right"></i></a>
    </div>

  </div>

  <hr>
  <% end %>

  <div class="row text-center">

    <div class="col-lg-12">
      <%= will_paginate @blogs, :class => 'pagination' %>
    </div>

  </div>

</div>
<!-- /.container -->

app/views/blog/show.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header"><%= @blog.title %></h1>
      <ol class="breadcrumb">
        <li><%= link_to 'Home', root_path %></li>
        <li class="active"><%= @blog.title %></li>
      </ol>
    </div>

  </div>

  <div class="row">

    <div class="col-lg-8">

      <!-- the actual blog post: title/author/date/content -->
      <hr>
      <p><i class="fa fa-clock-o"></i> Posted on <%= @blog.created_at.strftime("%B %d, %Y") %> by <a href="#"><%= @blog.admin_user.full_name %></a>
      </p>
      <hr>
      <% if @blog.image.present? %>
          <%= image_tag(@blog.image_url(:main), :class => 'img-responsive') %>
      <% else %>
          <img class="img-responsive" src="http://placehold.it/900x300">
      <% end %>
      <hr>
      <%= @blog.post.html_safe %>

      <hr>

      <!-- the comment box -->
      <!--<div class="well">-->
        <!--<h4>Leave a Comment:</h4>-->
        <!--<form role="form">-->
          <!--<div class="form-group">-->
            <!--<textarea class="form-control" rows="3"></textarea>-->
          <!--</div>-->
          <!--<button type="submit" class="btn btn-primary">Submit</button>-->
        <!--</form>-->
      <!--</div>-->

      <!--<hr>-->

      <!-- the comments -->
      <!--<h3>Start Bootstrap-->
        <!--<small>9:41 PM on August 24, 2013</small>-->
      <!--</h3>-->
      <!--<p>This has to be the worst blog post I have ever read. It simply makes no sense. You start off by talking about space or something, then you randomly start babbling about cupcakes, and you end off with random fish names.</p>-->

      <!--<h3>Start Bootstrap-->
        <!--<small>9:47 PM on August 24, 2013</small>-->
      <!--</h3>-->
      <!--<p>Don't listen to this guy, any blog with the categories 'dinosaurs, spaceships, fried foods, wild animals, alien abductions, business casual, robots, and fireworks' has true potential.</p>-->

    </div>

    <!--<div class="col-lg-4">-->
      <!--<div class="well">-->
        <!--<h4>Blog Search</h4>-->
        <!--<div class="input-group">-->
          <!--<input type="text" class="form-control">-->
                        <!--<span class="input-group-btn">-->
                            <!--<button class="btn btn-default" type="button"><i class="fa fa-search"></i>-->
                            <!--</button>-->
                        <!--</span>-->
        <!--</div>-->
        <!--&lt;!&ndash; /input-group &ndash;&gt;-->
      <!--</div>-->
      <!--&lt;!&ndash; /well &ndash;&gt;-->
      <!--&lt;!&ndash;<div class="well">&ndash;&gt;-->
        <!--&lt;!&ndash;<h4>Popular Blog Categories</h4>&ndash;&gt;-->
        <!--&lt;!&ndash;<div class="row">&ndash;&gt;-->
          <!--&lt;!&ndash;<%# @categories.each do |category| %>&ndash;&gt;-->
          <!--&lt;!&ndash;<div class="col-lg-6">&ndash;&gt;-->
            <!--&lt;!&ndash;<ul class="list-unstyled">&ndash;&gt;-->
              <!--&lt;!&ndash;<li><a href="#dinosaurs"><%#= category.name %></a></li>&ndash;&gt;-->
            <!--&lt;!&ndash;</ul>&ndash;&gt;-->
          <!--&lt;!&ndash;</div>&ndash;&gt;-->
          <!--&lt;!&ndash;<%# end %>&ndash;&gt;-->
        <!--&lt;!&ndash;</div>&ndash;&gt;-->
      <!--&lt;!&ndash;</div>&ndash;&gt;-->

    <!--</div>-->
  </div>

</div>
<!-- /.container -->